#!/bin/bash

PORT=80
FILE="/var/www/html/index.html"

nc -z 127.0.0.1 $PORT
if [ $? -ne 0 ]; then
  exit 1
fi

if [ ! -f "$FILE" ]; then
  exit 1
fi

exit 0

vrrp_script chk_web {
    script "/usr/local/bin/check_web.sh"
    interval 3
    weight -20
}

vrrp_instance VI_1 {
    state MASTER
    interface ens33
    virtual_router_id 15
    priority 150
    advert_int 1

    virtual_ipaddress {
        192.168.1.15/24
    }

    track_script {
        chk_web
    }
}


vrrp_script chk_web {
    script "/usr/local/bin/check_web.sh"
    interval 3
    weight -20
}

vrrp_instance VI_1 {
    state BACKUP
    interface ens33
    virtual_router_id 15
    priority 100
    advert_int 1

    virtual_ipaddress {
        192.168.1.15/24
    }

    track_script {
        chk_web
    }
}
